import { describe, expect, it } from 'vitest';
import { render, screen } from '@testing-library/react';

import { ImageMessage } from './image-message.js';

describe('ImageMessage', () => {
  it('renders the img with alt text when ready', () => {
    render(<ImageMessage src="https://example.test/cat.png" alt="A cat" />);
    const img = screen.getByAltText('A cat');
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute('src', 'https://example.test/cat.png');
  });

  it('shows generating state with spinner and progress %', () => {
    const { container } = render(
      <ImageMessage status="generating" alt="loading" progress={0.42} />,
    );
    expect(screen.getByText(/Generating/i)).toBeInTheDocument();
    // Lucide spinner present.
    expect(container.querySelector('.animate-spin')).not.toBeNull();
    // Progress fill width 42% — find any element whose inline width is 42%.
    const filled = Array.from(container.querySelectorAll<HTMLElement>('[style]')).some((el) =>
      /width:\s*42%/i.test(el.getAttribute('style') ?? ''),
    );
    expect(filled).toBe(true);
  });

  it('shows the error state with the message text', () => {
    render(<ImageMessage status="errored" alt="failed" error="quota exhausted" />);
    expect(screen.getByText(/Generation failed/i)).toBeInTheDocument();
    expect(screen.getByText(/quota exhausted/i)).toBeInTheDocument();
  });

  it('renders the caption when supplied', () => {
    render(<ImageMessage src="x" alt="ok" caption="Generated by Sonnet" />);
    expect(screen.getByText('Generated by Sonnet')).toBeInTheDocument();
  });

  it('renders a download anchor when downloadable + ready', () => {
    render(<ImageMessage src="https://example.test/cat.png" alt="cat" downloadable />);
    const link = screen.getByRole('link', { name: /Download image/i });
    expect(link).toHaveAttribute('href', 'https://example.test/cat.png');
    expect(link).toHaveAttribute('download');
  });
});
