import type { Meta, StoryObj } from '@storybook/react';
import { ImageGallery } from './image-gallery.js';
import type { MediaAttachment } from '@nyxis/core';

const meta = {
  title: 'AI · Multimodal/ImageGallery',
  component: ImageGallery,
  parameters: { layout: 'centered' },
  tags: ['autodocs'],
} satisfies Meta<typeof ImageGallery>;

export default meta;
type Story = StoryObj<typeof meta>;

const IMAGES: MediaAttachment[] = [
  {
    id: '1',
    kind: 'image',
    url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=640',
    name: 'circuit-board.jpg',
    alt: 'Brass circuit board.',
    width: 640,
    height: 426,
  },
  {
    id: '2',
    kind: 'image',
    url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=640',
    name: 'matrix-rain.jpg',
    alt: 'Matrix-style green text on black.',
    width: 640,
    height: 426,
  },
  {
    id: '3',
    kind: 'image',
    url: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=640',
    name: 'data-stream.jpg',
    alt: 'Abstract data stream.',
    width: 640,
    height: 426,
  },
  {
    id: '4',
    kind: 'image',
    url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=640',
    name: 'neural-grid.jpg',
    alt: 'Neural grid visualisation.',
    width: 640,
    height: 426,
  },
  {
    id: '5',
    kind: 'image',
    url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=640',
    name: 'ai-portrait.jpg',
    alt: 'Portrait generated by AI.',
    width: 640,
    height: 640,
  },
  {
    id: '6',
    kind: 'image',
    url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=640',
    name: 'mountain-night.jpg',
    alt: 'Snow-covered mountain at night.',
    width: 640,
    height: 426,
  },
];

export const Default: Story = {
  render: () => (
    <div className="w-[640px]">
      <ImageGallery images={IMAGES} />
    </div>
  ),
};

export const TwoColumns: Story = {
  render: () => (
    <div className="w-[480px]">
      <ImageGallery images={IMAGES.slice(0, 4)} columns={2} />
    </div>
  ),
};
